var LEVEL_BRO = [
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                              xxx               ",
	"                                               xxxx          o                  ",
	"                                        x             xAAAAAAx                  ",
	"                               xxx                    xxxxxxxx                  ",
	"                             o          o                                   c   ",
	" x            o       xxxx           xxxx                              xxxxxxx  ",
	" x  @       xxxxxx                                             xx      x     x  ",
	" x          x    x                                                     x     x  ",
	" xxxxxxxxxxxx    xxxxxxxxxxxxxxxxxx                    xxxxxxxxxxxxxxxxx     x  ",
	"                                  xAAAAAAAAAAAAAAAAAAAAx                     x  ",
	"                                  xxxxxxxxxxxxxxxxxxxxxx                        ",
	"                                                                                ",
	"                                                                                "],
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                      c         ",
    "                                                                     xx         ",
    "                                                                               ",
    "                                                               xxx              ",
    "                                                        o                       ",
    "                                                      xxxx                      ",
    "                                              o                                 ",
    "                                            xxxxx                               ",
    "                                    o                                           ",
    "                                 xxxxxx                                         ",
    "                          o                                                     ",
    "                       xxxxxx                                                   ",
    "                o                                                               ",
    "            xxxxxxx                                                             ",
    "   @                                                                            ",
	"  xxxxxxx                                                                       ",
    "                                                                                ",
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["                                                                                ",
    "                                                                                ",
	"                                                                                ",
	"                                                     xxxx        xxAxx          ",
	"                                                                                ",
	"                                                                 xx    xAx      ",
	"                                                           x                    ",
	"                                           c           x                        ",
	"     AAxx                                                    x     o            ",
	"                                                                xxxxxxx         ",
	"                       o           o             o                        xx    ",
	"                xxx         xxx          xxx          xxx      x    xxx         ",
	"                     o                o         o                               ",
	"                                                                                ",
	"      xxxxxxx       x     xxxxxxx         xxxxx                                 ",
	"                                                o  x                            ",
	"                                                       AxxA                     ",
	"                  xxxAxxx                     xxxxx                             ",                   
	"                            o           x                                       ",
	"           @                   xxx                                              ",
	"         xxxxxx                       AAxxxxAAA        xxxxxxx                  ",
	" xAAA   AAA   AAA   AAA   AAA   AAA   AAA   AAA   AAA   AAA   AAA   AAA   AAA x ",
	" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "],	
	["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	 "@                                                                              ",
	 "x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "x  xxxxxxxxxx          o     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "   xxxxxxxxxx   xxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "                xxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "xxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "xxxxxxxxxxxxxxxxxxxxxxxxxxx                        xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "                                                                               ",
	 "                                                 x                             ",
	 "                                           o  x                                ",
	 "xxx       xAAx      xx          xA   x                                         ",
	 "     o                     o                                                   ",
	 "         xxx        AxxA      xxx       AxA   ooo   xxx    xx   x     x   oo   ",
	 "               o           o       o                                           ",
	 "   AAx    xx        xx       xxx      xx      x      xxxx        AxA           ",
	 "                                                                               ",
	 "                                                                               ",
	 "AAAAAAAAAAAAxxxxxxx xxxxxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	 "AAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	 "                   c                                                           ",
	 "AAAAAAAAAAAAAAAAAAAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"]
	];

if (typeof module != "undefined" && module.exports) {
	module.exports = LEVEL_BRO
}